dts: sm-e7000: Use panel selection
msm8916-mainline/lk2nd pull request #144
Opened 2022-02-08 13:10 UTC by wonderfulShrineMaidenOfParadise

2022-02-28 16:02 UTC, stephan-gh requested changes

2022-02-28 16:02 UTC, stephan-gh commented on dts/msm8916/msm8916-samsung-r06.dts
> +				compatible = "samsung,ea8061-id400418";
Need longer compatibles!! ;)

```suggestion
				compatible = "samsung,ea8061-ams549bu19-id400418";
```

2022-02-28 16:07 UTC, stephan-gh approved these changes

2022-03-02 17:20 UTC, TravMurav approved these changes

2022-03-03 10:48 UTC, merged