Huawei G7 Plus / G8 / GX8 / Maimang 4: add Panel
msm8916-mainline/lk2nd pull request #468
Opened 2024-12-20 06:16 UTC by bzy-080408

added panel for these devices  
panel driver will be push to the repo later

2024-12-27 07:11 UTC, wonderfulShrineMaidenOfParadise requested changes

2024-12-27 07:11 UTC, wonderfulShrineMaidenOfParadise commented on lk2nd/device/dts/msm8916/msm8939-huawei-rio.dts
> +	model = "Huawei G7 Plus / G8 / GX8 / Maimang 4";
> Maimang 4

Would be better if it's written in the commit message, or split into another commit.

2024-12-27 07:12 UTC, wonderfulShrineMaidenOfParadise commented on lk2nd/device/dts/msm8916/msm8939-huawei-rio.dts
> +	model = "Huawei G7 Plus / G8 / GX8 / Maimang 4";
Other than that, looks good to me.

2024-12-29 05:41 UTC, wonderfulShrineMaidenOfParadise approved these changes

2024-12-31 05:25 UTC, merged

2024-12-31 05:26 UTC, TravMurav commented
Thanks!