Add SM-T355Y
msm8916-mainline/lk2nd pull request #65
Opened 2021-04-17 12:54 UTC by hello-world-321

Adds Samsung Tab A 8.0 (msm8916)

2021-04-19 17:39 UTC, Minecrell commented on dts/msm8916/msm8916-samsung-r04.dts
> +                compatible = "samsung,gt58lte-eur", "qcom,msm8916", "lk2nd,device";
As far as I can tell, the SM-T355Y is the Australian variant and is `msm8916-sec-gt58lte-aus-r00.dtsi`(i.e. `samsung,gt58lte-aus`) downstream. Do you have the Australian variant maybe?

2021-04-21 16:57 UTC, hello-world-321 reviewed
Changed the variant.

2021-04-21 17:21 UTC, TravMurav commented
Please make single commit with all the changes, make the commit description a bit more verbose (look how it was done for other devices), preferably use git and not the web ui. Indention is tabs and not spaces

2021-04-22 13:59 UTC, hello-world-321 commented
> Please make single commit with all the changes, make the commit description a bit more verbose (look how it was done for other devices), preferably use git and not the web ui. Indention is tabs and not spaces
> 
> Also avoid using master branch for new features even on your fork

Done

2021-04-22 14:04 UTC, TravMurav requested changes

2021-04-22 14:04 UTC, TravMurav commented on dts/msm8916/msm8916-samsung-r04.dts
> +                model = "Samsung Galaxy Tab A 8.0 2015 (SM-T355Y)";
Indention is tabs and not spaces

2021-04-22 18:38 UTC, hello-world-321 reviewed
Will use vscode to fix it tomorrow.

2021-04-23 06:13 UTC, hello-world-321 commented on dts/msm8916/msm8916-samsung-r04.dts
> +                model = "Samsung Galaxy Tab A 8.0 2015 (SM-T355Y)";
Resolved

2021-04-23 16:56 UTC, hello-world-321 commented
Fixed

2021-04-24 07:13 UTC, TravMurav approved these changes

2021-04-24 09:25 UTC, merged